name: mirror to other sites
on: push

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: mirroring to gitlab
        uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@gitlab.com:savfile/blog.git
          ssh_username: savfile

  mirror-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: mirroring to gitee
        uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@gitee.com:savfile/blog.git
          ssh_username: savfile

  mirror-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: mirroring to bitbucket
        uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@bitbucket.org:savfile/savfile.bitbucket.io.git
          ssh_username: savfile
